tlmgr update --all
tlmgr install collection-fontsrecommended 
tlmgr install texlive-times
tlmgr install lmodern
tlmgr install texinfo
tlmgr install texlive-base
tlmgr install texlive-extra-utils
tlmgr install texlive-fonts-extra
tlmgr install texlive-fonts-recommended
tlmgr install texlive-generic-recommended
tlmgr install texlive-latex-base
tlmgr install texlive-latex-extra
tlmgr install texlive-latex-recommended
